before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  -
    id: whatever
    main: "./whatever.go"
    binary: whatever
    ldflags:
      -X main.Date={{.CommitDate}}
    # mod_timestamp: "{{ .CommitTimestamp }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
